### ISSUE TITLE
Timestamps saved as millis instead of seconds, causes excess adverts in backend cache

### ISSUE THREAD

**Issue by agittins** [kvj/hass_Bluetooth_Proxy#3]
Howdy!

I had some issues with some users of my integration (https://github.com/agittins/bermuda) getting bogged down with stale adverts that I think may have come from this integration.

bdraco found that the issue seems to be the timestamps being saved as milliseconds instead of seconds, which caused the HA bluetooth backend to save out the adverts without expiring them, causing `/homeassistant/.storage/bluetooth.remote_scanners` to grow indefinitely, and to remain large even after the integration might have been removed.

HA has now merged a fix that will prevent restoring the stale adverts, so that should help existing sites, but this component should probably be fixed to prevent new records being saved out.

I think the issue is probably in https://github.com/kvj/hass_Bluetooth_Proxy/blob/f0170220dca36d2845132e1f3395ed160138c96b/custom_components/companion_bt_proxy/scanner.py#L28 where I am guessing it should convert the received data's timestamp from milliseconds to the local monotonic time (or maybe the companion app needs to change to send epoch seconds, then scanner.py converts to monotonic, I haven't dug into it).

The issue in HA is at https://github.com/home-assistant/core/issues/130432

If it's useful, I have a user's `bluetooth.remote_scanners` file of about 9MB containing 12k adverts over several months if you wanted to take a look, just let me know how best to send it to you (the user has OK'd sharing it with relevant devs).

A number of Bermuda users have been interested in using your integration to make use of their Android wall-tablets etc as proxies, so I'm keen to try it out and see if Bermuda can make use of the advert info!

**Comment by kvj** [comment]
Looking into it

**Comment by agittins** [comment]
Thanks for the quick follow-up!

This might be a dumb question, but...
- HA's monotonic time is a float of "seconds since HA started up"
- Your Android app's timestamp is (from memory, I only looked at it briefly several days ago) "milliseconds since Android started up"?
- The latest patch converts the timestamp from milliseconds to seconds without also converting between system-boot-times

Is there a conversion between the two systems' boot-times already being done elsewhere, or do both ends need to normalise against epoch time and their local boot time for a full fix?

**Comment by open-forest** [comment]
@kvj @agittins It would be great if you could coordinate on solving this, although the bug seems to be on the @kvj side. In HomeAssistant, the HA Bluetooth Proxy advertisements are marked as happening -1755527460.31 seconds ago (which basically means 56 years in the future), while at the same time a regular ESPHome Bluetooth proxy is marked as advertising .70 seconds ago.

(Current epoch time is 1756335600 seconds, so it seems the conversion is straightforward: convert from Android boot time to epoch time.)

I modified the Companion Integration code and I hope that has fixed the issue.
